[WIP] StudioResource pivot table
AnimeThemes/animethemes-server pull request #277
Opened 2021-11-05 22:05 UTC by ProWeebDev

This pivot class will allow a studio to have multiple external resources attached to it.

2021-11-07 23:40 UTC, paranarimasu commented on app/Console/Commands/Wiki/DatabaseDumpCommand.php
> +        StudioResource::TABLE,
Can we keep this in alphabetical order?

2021-11-08 00:22 UTC, ProWeebDev commented on app/Console/Commands/Wiki/DatabaseDumpCommand.php
> +        StudioResource::TABLE,
Fixed

2021-11-08 17:14 UTC, paranarimasu requested changes
Initial review completed

2021-11-10 04:37 UTC, paranarimasu requested changes
Second review. I followed through with code inspection, static analysis and test case runs.

2021-11-10 04:37 UTC, paranarimasu commented on app/Models/Wiki/Studio.php
> + * @property BasePivot $pivot
Undefined Class BasePivot. It needs to be imported.

2021-11-10 04:37 UTC, paranarimasu commented on app/Pivots/StudioResource.php
> + * @method static StudioResourceFactory factory(...$parameters)
Undefined class StudioResourceFactory. It needs to be imported.

2021-11-10 04:37 UTC, paranarimasu commented on app/Nova/Resources/Wiki/Studio.php
> +                            ->rules(['nullable', 'max:192'], )
Code smell: useless trailing comma.

2021-11-10 04:37 UTC, paranarimasu commented on tests/Feature/Jobs/Pivot/StudioResourceTest.php
> +     */
Static Analysis: Add return typehint "@return void".

2021-11-10 04:37 UTC, paranarimasu commented on tests/Feature/Jobs/Pivot/StudioResourceTest.php
> +     */
Static Analysis: Add return typehint "@return void".

2021-11-10 04:37 UTC, paranarimasu commented on app/Nova/Resources/Wiki/Studio.php
> +            BelongsToMany::make(__('nova.external_resources', 'Resources', ExternalResource::class))
Erroneous closing parenthesis at the end of the line. There should be a closing parenthesis after 'nova.external_resources' as this is the translation key for the __() translation helper function.

2021-11-10 17:54 UTC, paranarimasu requested changes
Acceptance testing findings. This should be the final review.

2021-11-10 17:54 UTC, paranarimasu commented on app/Nova/Resources/Wiki/ExternalResource.php
> +            BelongsToMany::make(__('nova.studio'), 'Studio', Studio::class)
Acceptance test finding: 'Studio' needs to be 'Studios'. This throws an exception when viewing an external resource in nova.

2021-11-10 17:54 UTC, paranarimasu commented on app/Http/Api/Schema/Wiki/StudioSchema.php
We need to add the StudioResource::ATTRIBUTE_AS field to the fields function. As it is right now, attempting to select this field for sparse fieldsets produces a validation error. 

Please use the same approach as AnimeSchema does to include the pivot field.

2021-11-11 17:34 UTC, paranarimasu approved these changes
Code analysis passed. Static Analysis passed. Tests passed. Acceptance passed.

PR approved.

2021-11-11 17:35 UTC, merged